---

- name: Pull shairport & snapcast docker images
  docker_image:
    name: '{{ item }}'
  with_items:
  - brandonfryslie/snapcast-client
  - brandonfryslie/snapcast-server
  - brandonfryslie/shairport-sync

- name: Transfer Boom-waffle startup scripts
  become: yes
  become_method: sudo
  copy: src=./ dest=/home/pi/boom-waffle-startup/ mode=0755

- name: Enable Boom-waffle common startup script
  become: yes
  lineinfile:
    dest: '/etc/rc.local'
    insertafter: '\/bin\/'  # after /bin/sh or /bin/bash line
    line: '/home/pi/boom-waffle-startup/common-start-boom-waffle.sh'

- name: Run Boom-waffle common startup script now
  become: yes
  shell: '/home/pi/boom-waffle-startup/common-start-boom-waffle.sh'
