---

- name: Disable power-saving mode on wlan0 / wlan1 at boot
  become: yes
  blockinfile:
    dest: '/etc/rc.local'
    insertafter: '\/bin\/'  # after /bin/sh or /bin/bash line
    block: |
      iw dev wlan0 set power_save off || true
      iw dev wlan1 set power_save off || true

- name: Disable power-saving mode on wlan0 / wlan1 now
  become: yes
  shell: iw dev wlan0 set power_save off || true; iw dev wlan1 set power_save off || true
